const dataTeams = [
    {
        id: 1,
        name: 'María Eva González',
        title: 'María Eva González, directora',
        image: '/images/Team/Eva.jpeg',
        text: 'Directora',
        Twitter: 'https://twitter.com/vitapilar',
        LinkedIn: 'https://www.linkedin.com/in/mariaevagonzalez/',
        Instagram: 'https://www.instagram.com/mariaevagonzalezok/',
        YouTube: 'https://www.youtube.com/channel/UCwaYxnfzInk0pF8lZkr2EAQ',
    },
    {
        id: 2,
        name: 'María Ivana Croxcatto',
        title: 'María Ivana Croxcatto, Líder de Proyecto',
        image: '/images/Team/Ivana.jpeg',
        text: 'Líder de Proyecto',
        LinkedIn: 'https://www.linkedin.com/in/mariaivanacroxcatto/',
        Medium: 'https://writing-zen.medium.com/',
        GitHub: 'https://github.com/ma-ivana',
    },
    {
        id: 3,
        name: 'Marina Lemos',
        title: 'Marina Lemos, Líder de Sustentabilidad',
        image: '/images/Team/Marina.jpeg',
        text: 'Desarrollo Organizacional',
        Twitter: '',
        LinkedIn: '',
        Instagram: '',
    },
    {
        id: 4,
        name: 'Sonia Johannes',
        title: 'Sonia Johannes, Finanzas',
        image: '/images/Team/Sonia.jpeg',
        text: 'Finanzas',
        Twitter: '',
        LinkedIn: '',
        Instagram: '',
    },
    {
        id: 5,
        name: 'Melina Croxcatto',
        title: 'Melina Croxcatto, Desarrollo Organizacional',
        image: '/images/Team/Melina.jpeg',
        text: 'Desarrollo Organizacional',
        Twitter: '',
        LinkedIn: 'https://www.linkedin.com/in/melina-c-0b8ab62',
        Instagram: '',
    },
    {
        id: 6,
        name: 'Fabiana Basile',
        title: 'Fabiana Basile, Líder de Eventos',
        image: '/images/Team/Fabiana.jpeg',
        text: 'Líder de Eventos',
        Twitter: '',
        LinkedIn: '',
        Instagram: '',
    },
    {
        id: 7,
        name: 'Verónica Castro',
        title: 'Verónica Castro, Desarrollo de Programas STEM',
        image: '/images/Team/Veronica.jpeg',
        text: 'Líder de Desarrollo de Programas STEM',
        Twitter: '',
        LinkedIn: '',
        Instagram: '',
    },
    {
        id: 8,
        name: 'Claudia Edith Julian',
        title: 'Claudia Edith Julian, Líder de Desarrollo',
        image: '/images/Team/Claudia.jpeg',
        text: 'Líder de Desarrollo',
        Twitter: '',
        LinkedIn: '',
        Instagram: '',
    },
    {
        id: 9,
        name: 'Fiorella Yandal',
        title: 'Fiorella Yandal, Aprediz',
        image: '/images/Team/Fiorella.jpeg',
        text: 'Aprediz',
        Twitter: '',
        LinkedIn: '',
        Instagram: '',
    }
]
export default dataTeams;